KEY_WORD("main"  , 4 , "main"  , MAIN      )
KEY_WORD("return", 6 , "return", RETURN    )
KEY_WORD(";"     , 1 , ";"     , SEMICOLON )
KEY_WORD("printf", 5 , "print" , PRINT     )
KEY_WORD("scanf" , 4 , "scan"  , SCAN      )
KEY_WORD("if"    , 2 , "if"    , IF        )
KEY_WORD("else"  , 4,  "else"  , ELSE      )
KEY_WORD("while" , 5 , "while" , WHILE     )
KEY_WORD("="     , 1 , "="     , ASSIGN    )
KEY_WORD("{"     , 1 , "{"     , LSB       )
KEY_WORD("}"     , 1 , "}"     , RSB       )
KEY_WORD("("     , 1 , "("     , LB        )
KEY_WORD(")"     , 1 , ")"     , RB        )
KEY_WORD("["     , 1 , "["     , LAB       )
KEY_WORD("]"     , 1 , "]"     , RAB       )
KEY_WORD(","     , 1 , ","     , COMMA     )
KEY_WORD("+"     , 1 , "+"     , ADD       )
KEY_WORD("-"     , 1 , "-"     , SUB       )
KEY_WORD("*"     , 1 , "*"     , MUL       )
KEY_WORD("/"     , 1 , "/"     , DIV       )
KEY_WORD("^"     , 1 , "^"     , POW       )
KEY_WORD(">"     , 1 , ">"     , BAA       )
KEY_WORD("<"     , 1 , "<"     , BAB       )
KEY_WORD("=="    , 2 , "=="    , BAE       )
KEY_WORD(">="    , 2 , ">="    , BAAE      )
KEY_WORD("<="    , 2 , "<="    , BABE      )
KEY_WORD("!="    , 2 , "!="    , BANE      )
KEY_WORD("||"    , 2 , "||"    , OR        )
KEY_WORD("&&"    , 2 , "&&"    , AND       )
KEY_WORD("!"     , 1 , "!"     , NOT       )
KEY_WORD("ln"    , 2 , "ln"    , LN        )
KEY_WORD("sin"   , 3 , "sin"   , SIN       )
KEY_WORD("cos"   , 3 , "cos"   , COS       )
