//KEY_WORD("main"  , 4 , "main"  , FUNC            , MAIN   )
//KEY_WORD("return", 6 , "return", ?               , RETURN )
KEY_WORD(";"     , 1 , ";"     , LR              , LR     )
//KEY_WORD("print" , 5 , "print" , FUNC            , PRINT  )
//KEY_WORD("printf", 6 , "printf", FUNC            , PRINTF )
//KEY_WORD("scan"  , 4 , "scan"  , FUNC            , SCAN   )
KEY_WORD("if"    , 2 , "if"    , CON_OPERATOR    , IF     )
KEY_WORD("while" , 5 , "while" , CYCLE           , WHILE  )
KEY_WORD("="     , 1 , "="     , BINARY_OPERATION, ASSIGN )
KEY_WORD("{"     , 1 , "{"     , SEPARATOR       , LSB    )
KEY_WORD("}"     , 1 , "}"     , SEPARATOR       , RSB    )
KEY_WORD("("     , 1 , "("     , SEPARATOR       , LB     )
KEY_WORD(")"     , 1 , ")"     , SEPARATOR       , RB     )
KEY_WORD(","     , 1 , ","     , SEPARATOR       , COMMA  )
KEY_WORD("+"     , 1 , "+"     , BINARY_OPERATION, ADD    )
KEY_WORD("-"     , 1 , "-"     , BINARY_OPERATION, SUB    )
KEY_WORD("*"     , 1 , "*"     , BINARY_OPERATION, MUL    )
KEY_WORD("/"     , 1 , "/"     , BINARY_OPERATION, DIV    )
KEY_WORD("^"     , 1 , "^"     , BINARY_OPERATION, POW    )
KEY_WORD(">"     , 1 , ">"     , BINARY_OPERATION, BAA    )
KEY_WORD("<"     , 1 , "<"     , BINARY_OPERATION, BAB    )
KEY_WORD("=="    , 2 , "=="    , BINARY_OPERATION, BAE    )
KEY_WORD(">="    , 2 , ">="    , BINARY_OPERATION, BAAE   )
KEY_WORD("<="    , 2 , "<="    , BINARY_OPERATION, BABE   )
KEY_WORD("!="    , 2 , "!="    , BINARY_OPERATION, BANE   )
KEY_WORD("ln"    , 2 , "ln"    , UNARY_OPERATION , LN     )
KEY_WORD("sin"   , 3 , "sin"   , UNARY_OPERATION , SIN    )
KEY_WORD("cos"   , 3 , "cos"   , UNARY_OPERATION , COS    )
KEY_WORD("tg"    , 2 , "tg"    , UNARY_OPERATION , TG     )
KEY_WORD("ctg"   , 3 , "ctg"   , UNARY_OPERATION , CTG    )
KEY_WORD("arcsin", 6 , "arcsin", UNARY_OPERATION , ARCSIN )
KEY_WORD("arccos", 6 , "arccos", UNARY_OPERATION , ARCCOS )
KEY_WORD("arctg" , 5 , "arctg" , UNARY_OPERATION , ARCTG  )
KEY_WORD("arcctg", 6 , "arcctg", UNARY_OPERATION , ARCCTG )
KEY_WORD("sh"    , 2 , "sh"    , UNARY_OPERATION , SH     )
KEY_WORD("ch"    , 2 , "ch"    , UNARY_OPERATION , CH     )
KEY_WORD("th"    , 2 , "th"    , UNARY_OPERATION , TH     )
KEY_WORD("cth"   , 3 , "cth"   , UNARY_OPERATION , CTH    )
KEY_WORD("sqrt"  , 4 , "sqrt"  , UNARY_OPERATION , SQRT   )
KEY_WORD("exp"   , 3 , "exp"   , UNARY_OPERATION , EXP    )
