KEY_WORD("main"  , 4 , "main"  , FUNC            , MAIN      )
KEY_WORD("return", 6 , "return", UNARY_OPERATION , RETURN    )
KEY_WORD(";"     , 1 , ";"     , LR              , SEMICOLON )
KEY_WORD("print" , 5 , "print" , FUNC            , PRINT     )
KEY_WORD("printf", 6 , "printf", FUNC            , PRINTF    )
KEY_WORD("scan"  , 4 , "scan"  , FUNC            , SCAN      )
KEY_WORD("if"    , 2 , "if"    , CON_OPERATOR    , IF        )
KEY_WORD("while" , 5 , "while" , LOOP            , WHILE     )
KEY_WORD("="     , 1 , "="     , BINARY_OPERATION, ASSIGN    )
KEY_WORD("{"     , 1 , "{"     , SEPARATOR       , LSB       )
KEY_WORD("}"     , 1 , "}"     , SEPARATOR       , RSB       )
KEY_WORD("("     , 1 , "("     , SEPARATOR       , LB        )
KEY_WORD(")"     , 1 , ")"     , SEPARATOR       , RB        )
KEY_WORD(","     , 1 , ","     , SEPARATOR       , COMMA     )
KEY_WORD("+"     , 1 , "+"     , BINARY_OPERATION, ADD       )
KEY_WORD("-"     , 1 , "-"     , BINARY_OPERATION, SUB       )
KEY_WORD("*"     , 1 , "*"     , BINARY_OPERATION, MUL       )
KEY_WORD("/"     , 1 , "/"     , BINARY_OPERATION, DIV       )
KEY_WORD("^"     , 1 , "^"     , BINARY_OPERATION, POW       )
KEY_WORD(">"     , 1 , ">"     , BINARY_OPERATION, BAA       )
KEY_WORD("<"     , 1 , "<"     , BINARY_OPERATION, BAB       )
KEY_WORD("=="    , 2 , "=="    , BINARY_OPERATION, BAE       )
KEY_WORD(">="    , 2 , ">="    , BINARY_OPERATION, BAAE      )
KEY_WORD("<="    , 2 , "<="    , BINARY_OPERATION, BABE      )
KEY_WORD("!="    , 2 , "!="    , BINARY_OPERATION, BANE      )
KEY_WORD("ln"    , 2 , "ln"    , FUNC            , LN        )
KEY_WORD("sin"   , 3 , "sin"   , FUNC            , SIN       )
KEY_WORD("cos"   , 3 , "cos"   , FUNC            , COS       )
KEY_WORD("tg"    , 2 , "tg"    , FUNC            , TG        )
KEY_WORD("ctg"   , 3 , "ctg"   , FUNC            , CTG       )
KEY_WORD("arcsin", 6 , "arcsin", FUNC            , ARCSIN    )
KEY_WORD("arccos", 6 , "arccos", FUNC            , ARCCOS    )
KEY_WORD("arctg" , 5 , "arctg" , FUNC            , ARCTG     )
KEY_WORD("arcctg", 6 , "arcctg", FUNC            , ARCCTG    )
KEY_WORD("sh"    , 2 , "sh"    , FUNC            , SH        )
KEY_WORD("ch"    , 2 , "ch"    , FUNC            , CH        )
KEY_WORD("th"    , 2 , "th"    , FUNC            , TH        )
KEY_WORD("cth"   , 3 , "cth"   , FUNC            , CTH       )
KEY_WORD("sqrt"  , 4 , "sqrt"  , FUNC            , SQRT      )
KEY_WORD("exp"   , 3 , "exp"   , FUNC            , EXP       )
