KEY_WORD("main"  , 4 , "main"  , FUNC            , MAIN      )
KEY_WORD("return", 6 , "return", UNARY_OPERATION , RETURN    )
KEY_WORD(";"     , 1 , ";"     , SEPARATOR       , SEMICOLON )
KEY_WORD("print" , 5 , "print" , FUNC            , PRINT     )
KEY_WORD("scan"  , 4 , "scan"  , FUNC            , SCAN      )
KEY_WORD("if"    , 2 , "if"    , CON_OPERATOR    , IF        )
KEY_WORD("while" , 5 , "while" , LOOP            , WHILE     )
KEY_WORD("="     , 1 , "="     , BINARY_OPERATION, ASSIGN    )
KEY_WORD("{"     , 1 , "{"     , SEPARATOR       , LSB       )
KEY_WORD("}"     , 1 , "}"     , SEPARATOR       , RSB       )
KEY_WORD("("     , 1 , "("     , SEPARATOR       , LB        )
KEY_WORD(")"     , 1 , ")"     , SEPARATOR       , RB        )
KEY_WORD(","     , 1 , ","     , SEPARATOR       , COMMA     )
KEY_WORD("+"     , 1 , "+"     , BINARY_OPERATION, ADD       )
KEY_WORD("-"     , 1 , "-"     , BINARY_OPERATION, SUB       )
KEY_WORD("*"     , 1 , "*"     , BINARY_OPERATION, MUL       )
KEY_WORD("/"     , 1 , "/"     , BINARY_OPERATION, DIV       )
KEY_WORD("^"     , 1 , "^"     , BINARY_OPERATION, POW       )
KEY_WORD(">"     , 1 , ">"     , BINARY_OPERATION, BAA       )
KEY_WORD("<"     , 1 , "<"     , BINARY_OPERATION, BAB       )
KEY_WORD("=="    , 2 , "=="    , BINARY_OPERATION, BAE       )
KEY_WORD(">="    , 2 , ">="    , BINARY_OPERATION, BAAE      )
KEY_WORD("<="    , 2 , "<="    , BINARY_OPERATION, BABE      )
KEY_WORD("!="    , 2 , "!="    , BINARY_OPERATION, BANE      )
KEY_WORD("||"    , 2 , "||"    , BINARY_OPERATION, OR        )
KEY_WORD("&&"    , 2 , "&&"    , BINARY_OPERATION, AND       )
KEY_WORD("!"     , 1 , "!"     , UNARY_OPERATION , NOT       )
KEY_WORD("ln"    , 2 , "ln"    , FUNC            , LN        )
KEY_WORD("sin"   , 3 , "sin"   , FUNC            , SIN       )
KEY_WORD("cos"   , 3 , "cos"   , FUNC            , COS       )
